# Generated by Django 2.0 on 2018-11-01 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181101_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='abc123', max_length=64, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='contact',
            field=models.CharField(default='99889988', max_length=512, verbose_name='Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='phone',
            field=models.CharField(default='9988998899', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')], verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
